"""Gerrit 메타데이터 수집 회귀 테스트. 자격증명·실제 서버 불필요."""
import contextlib
import datetime as dt
import io
import json
import sys
import tempfile
import unittest
from pathlib import Path
from unittest.mock import Mock, patch

import requests

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import gerrit_signal as signal


NOW = dt.datetime(2026, 9, 15, tzinfo=dt.timezone.utc)
RECENT = "2026-09-10 01:02:03.123456789"
OLD = "2025-01-01 00:00:00.000000000"


def raw_change(number=1, **extra):
    return {"_number": number, "project": "project", "status": "MERGED",
            "owner": {"email": "owner@example.test"}, "submitted": RECENT,
            "submitter": {"email": "integrator@example.test"}, **extra}


class GerritSignalTests(unittest.TestCase):
    def test_decode_xssi(self):
        self.assertEqual(signal._decode_json(")]}'\n[1]"), [1])

    def test_pagination_with_server_cap_and_duplicates(self):
        client = Mock(name="na")
        client.get.side_effect = [
            [raw_change(1), raw_change(2, _more_changes=True)],
            [raw_change(2), raw_change(3, _more_changes=True)],
            [raw_change(4)],
        ]
        changes, truncated = signal.fetch_recent_changes(client, 180, 0)
        self.assertEqual([c["_number"] for c in changes], [1, 2, 3, 4])
        self.assertFalse(truncated)
        self.assertEqual([call.kwargs["params"]["S"] for call in client.get.call_args_list], [0, 2, 4])

    def test_change_limit_is_explicit(self):
        client = Mock()
        client.get.return_value = [raw_change(1, _more_changes=True)]
        changes, truncated = signal.fetch_recent_changes(client, 180, 1)
        self.assertEqual(len(changes), 1)
        self.assertTrue(truncated)

    def test_stalled_pagination_fails(self):
        client = Mock()
        client.get.return_value = [raw_change(1, _more_changes=True)]
        with self.assertRaises(signal.CollectionError):
            signal.fetch_recent_changes(client, 180, 0)

    def test_messages_votes_and_membership_metadata(self):
        raw = raw_change(
            subject="PRIVATE BODY", messages=[{"id": "m", "message": "PRIVATE BODY", "date": RECENT,
                                               "author": {"email": "reviewer@example.test"}}],
            labels={"Code-Review": {"all": [{"email": "reviewer@example.test", "value": 2}]}},
            reviewers={"REVIEWER": [{"email": "assigned@example.test"}]},
            reviewer_updates=[{"reviewer": {"email": "assigned@example.test"}, "state": "REVIEWER", "updated": RECENT}],
        )
        result = signal.change_metadata(raw, "na")
        self.assertNotIn("PRIVATE BODY", json.dumps(result))
        self.assertEqual(result["votes"][0]["value"], 2)
        self.assertEqual(result["reviewer_updates"][0]["state"], "REVIEWER")
        self.assertTrue(result["merged"])
        self.assertTrue(result["submitter_known"])

    def test_all_patchsets_comments_replies_and_robot_body_removed(self):
        client = Mock()
        client.get.return_value = {"file.c": [
            {"id": "a", "patch_set": 1, "message": "PRIVATE BODY", "author": {"email": "one"}},
            {"id": "b", "patch_set": 2, "in_reply_to": "a", "unresolved": False,
             "robot_id": "checker", "fix_suggestions": [{"replacement": "PRIVATE BODY"}]},
        ], "/PATCHSET_LEVEL": [{"id": "c", "patch_set": 3}]}
        results = signal.fetch_comments(client, 123)
        self.assertEqual(len(results), 3)
        self.assertEqual(results[1]["in_reply_to"], "a")
        self.assertNotIn("PRIVATE BODY", json.dumps(results))
        client.get.assert_called_once_with("123/comments", optional=False)

    def test_aggregation_distinguishes_roles_and_filters_old_events(self):
        change = signal.change_metadata(raw_change(
            labels={"Code-Review": {"all": [
                {"email": "reviewer@example.test", "value": 2},
                {"email": "pending@example.test", "value": 0},
            ]}},
            messages=[
                {"author": {"email": "reviewer@example.test"}, "date": RECENT, "tag": "autogenerated:gerrit:review"},
                {"author": {"email": "uploader@example.test"}, "date": RECENT, "tag": "autogenerated:gerrit:newPatchSet"},
                {"author": {"email": "old@example.test"}, "date": OLD},
            ],
        ), "na")
        change["comments"] = [
            {"author": {"email": "reviewer@example.test"}, "updated": RECENT},
            {"author": {"email": "reviewer@example.test"}, "updated": RECENT},
            {"author": {"email": "owner@example.test"}, "updated": RECENT},
            {"author": {"email": "old@example.test"}, "updated": OLD},
        ]
        change["robot_comments"] = [{"author": {"email": "bot@example.test"}, "updated": RECENT}]
        result = signal.aggregate([change], 180, NOW)
        self.assertEqual(result["person_total"], {"owner@example.test": 1})
        self.assertEqual(result["merged_owner_total"], {"owner@example.test": 1})
        self.assertEqual(result["submitter_total"], {"integrator@example.test": 1})
        self.assertEqual(result["reviewer_total"], {"reviewer@example.test": 1})
        self.assertEqual(result["comment_total"], {"reviewer@example.test": 2, "owner@example.test": 1})
        self.assertEqual(result["robot_comment_total"], {"bot@example.test": 1})
        self.assertEqual(result["message_total"]["uploader@example.test"], 1)

    def test_unknown_submitter_never_falls_back_to_owner(self):
        change = signal.change_metadata(raw_change(submitter={}), "na")
        result = signal.aggregate([change], 180, NOW)
        self.assertEqual(result["unknown_submitter_changes"], 1)
        self.assertEqual(result["submitter_total"], {})

    def test_old_merge_and_unmerged_status(self):
        changes = [signal.change_metadata(raw_change(submitted=OLD), "na"),
                   signal.change_metadata(raw_change(2, status="NEW"), "na")]
        result = signal.aggregate(changes, 180, NOW)
        self.assertEqual(result["submitter_total"], {})
        self.assertEqual(result["merged_owner_total"], {"owner@example.test": 1})
        self.assertEqual(result["status_counts"], {"MERGED": 1, "NEW": 1})

    def test_fallback_account_ids_are_server_scoped(self):
        self.assertEqual(signal.person_key({"_account_id": 7}, "na"), "na:account:7")
        self.assertNotEqual(signal.person_key({"_account_id": 7}, "na"), signal.person_key({"_account_id": 7}, "lamp"))

    def test_http_and_network_errors_are_sanitized(self):
        client = signal.GerritClient("na", {"url": "https://gerrit.example.test", "usr": "user", "pw": "secret"})
        self.addCleanup(client.session.close)
        with patch.object(client.session, "get", return_value=Mock(status_code=403, text="secret")):
            with self.assertRaises(signal.CollectionError) as error:
                client.get()
            self.assertNotIn("secret", str(error.exception))
        with patch.object(client.session, "get", side_effect=requests.ConnectionError("secret")):
            with self.assertRaises(signal.CollectionError) as error:
                client.get()
            self.assertNotIn("secret", str(error.exception))

    def test_optional_robot_endpoint_only_tolerates_unsupported(self):
        client = signal.GerritClient("na", {"url": "https://gerrit.example.test", "usr": "user", "pw": "secret"})
        self.addCleanup(client.session.close)
        with patch.object(client.session, "get", return_value=Mock(status_code=404)):
            self.assertIsNone(client.get("1/robotcomments", optional=True))
            with self.assertRaises(signal.CollectionError):
                client.get("1/comments")

    def test_successful_empty_server_is_reachable(self):
        client = Mock()
        client.get.return_value = []
        with patch.object(signal, "_load_gerrit_conf", return_value={"na": {}}), \
                patch.object(signal, "GerritClient", return_value=client):
            result = signal.collect_signal(["na"], 180, 1)
        self.assertEqual(result["reachable_servers"], ["na"])
        self.assertEqual(result["changes"], [])
        client.session.close.assert_called_once()

    def test_failed_collection_preserves_previous_json(self):
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "signal.json"
            path.write_text("previous", encoding="utf-8")
            with patch.object(sys, "argv", ["script", "--server", "na", "--json-out", str(path)]), \
                    patch.object(signal, "collect_signal", side_effect=signal.CollectionError("failure")), \
                    contextlib.redirect_stderr(io.StringIO()):
                self.assertEqual(signal.main(), 1)
            self.assertEqual(path.read_text(encoding="utf-8"), "previous")


if __name__ == "__main__":
    unittest.main()